groups:
    - developer
    - bash
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        # - dotfiles::projects
        - osxdefaults::set_computer_name
attributes:
    authorization:
        sudo:
            users:
                - tegamckinney
            passwordless: true
            include_sudoers_d: true
    git:
        name: Tega McKinney
        email: tega.mckinney@freshedgesolutions.com
    dotfiles:
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
        # projects:
        #     -
        #         - kitchenplan-config
        #         - https://github.com/tegamckinney/kitchenplan-config.git
        #     -
        #         - kitchenplan
        #         - https://github.com/tegamckinney/kitchenplan.git
        #     -
        #         - chef-applications
        #         - https://github.com/tegamckinney/chef-applications.git
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - charles
            - cord
    sublime_text:
        preferences:
            font_size: 14
            ignored_packages: []
            remember_open_files: false
            tab_size: 2
            vintage_start_in_command_mode: false
            vintage_use_clipboard: false
    osxdefaults:
        computername: Snoopy
